// spa/src/components/PermissionsModal.vue
<template>
    <vue-final-modal v-model="show" name="permissionsModal" content-class="modal-content" classes="modal-container" @beforeOpen="handleOpen">
      <div v-for="value, key in params.permissions" :key="key">
        <a>{{ key }}</a>{{ " " }}
        <!-- <input :value="value" @input="params.permissions[key] = $event.target.value"> -->
        <label>Чтение</label>
        <input type="checkbox" :checked="value.show" @input="params.permissions[key].show = $event.target.checked" />
        <label>Запись</label>
        <input type="checkbox" :checked="value.write" @input="params.permissions[key].write = $event.target.checked" />
      </div>
      <div>
        <input v-model="newuser" />{{ " " }}
        <button @click="params.permissions[newuser] = {show: true, write: false}; newuser = ''">Добавить роль</button>
      </div>
      <VButtonDanger @click="handleClick(true)">Изменить</VButtonDanger>
      <VButton @click="handleClick(false)">Закрыть</VButton>
    </vue-final-modal>
</template>
<style>
.title {
  font-size: 1.5rem;
  margin-bottom: 1rem;
}

.modal-content {
  position: relative;
  display: flex;
  flex-direction: column;
  max-height: 90%;
  margin: 0 1rem;
  margin-top: 1.5rem;
  padding: 1rem;
  border: 1px solid #e2e8f0;
  border-radius: .25rem;
  background: #fff;
}

.modal-container {
  display: flex;
  justify-content: center;
  align-items: flex-start;
}
</style>
<script lang="ts">
import { defineComponent } from 'vue'
import VButtonDanger from './VButtonDanger.vue';
import VButton from './VButton.vue';

export default defineComponent({
    components: { VButton, VButtonDanger },
    data() {
        return {
            show: false,
            newuser: "",
            params: {
              permissions: {},
              // eslint-disable-next-line
              cb: (x: any) => void 0
            }
        }
    }, 
    methods: {
      handleClick(answer: boolean) {
        if(answer) {
          this.params.cb(this.params.permissions);
        }
        this.show = false;
      },
      // eslint-disable-next-line
      handleOpen(event: any) {
        this.params = event.ref.params;
      }
    }
})
</script>

// svelte/src/components/modals/PermissionsModal.svelte
<script lang="ts">
    import Button from "../Button.svelte";
    import type { Terminal } from "../../api/terminals";
    import Loading from "../helpers/Loading.svelte";
    import { events } from "../../events";

    const handleClick = (success: boolean) => async () => {
        if (success && terminalInfo != null) {
            loading = true;
            await terminalInfo.setPermissions(permissions);
            loading = false;
        }
        terminalInfo = null;
    };

    let loading = false;
    let terminalInfo: Terminal | null;
    let permissions: { [key: string]: { show: boolean; write: boolean } } = {};
    let newuser = "";

    events.on("changeTerminalPermissions", (terminal) => {
        terminalInfo = terminal;
        permissions = {};
        terminal.getPermissions().then((perm) => {
            // HACK
            permissions = perm as any;
        });
    });
</script>

{#if terminalInfo}
    <div class="modal-container">
        <div class="modal-content">
            <div class="title">Права для {terminalInfo.name}</div>
            {#each Object.entries(permissions) as [key, value]}
                <div>
                    <span>{key}</span>{" "}
                    <label for={key + "_read"}>Чтение</label>
                    <input
                        type="checkbox"
                        bind:checked={value.show}
                        id={key + "_read"}
                        disabled={loading}
                    />
                    <label for={key + "_write"}>Запись</label>
                    <input
                        type="checkbox"
                        bind:checked={value.write}
                        id={key + "_write"}
                        disabled={loading}
                    />
                </div>
            {/each}
            <div>
                <input bind:value={newuser} disabled={loading} />{" "}
                <button
                    disabled={loading}
                    on:click={() => {
                        permissions[newuser] = { show: true, write: false };
                        newuser = "";
                    }}>Добавить роль</button
                >
            </div>
            <Button danger on:click={handleClick(true)}>
                Отправить
                <Loading {loading} />
            </Button>
            <Button on:click={handleClick(false)}>Отмена</Button>
        </div>
    </div>
{/if}

<style>
    .title {
        font-size: 1.5rem;
        margin-bottom: 1rem;
    }

    .modal-content {
        position: relative;
        display: flex;
        flex-direction: column;
        max-height: 90%;
        margin: 0 1rem;
        margin-top: 1.5rem;
        padding: 1rem;
        border: 1px solid #e2e8f0;
        border-radius: 0.25rem;
        background: #fff;
    }

    .modal-container {
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        display: flex;
        justify-content: center;
        align-items: flex-start;
    }

    label {
        display: unset;
    }
</style>
