// spa/src/App.vue
<template>
  <div>
    <RestartModal />
    <EditModal />
    <PermissionsModal />
    <UserModal />
    <Container>
      <UsersCollapse v-if="isAdmin" />
      <ServerCollapse
        v-for="server in servers"
        :key="server.id"
        :server="server"
      />
    </Container>
  </div>
</template>

<style>
@import url("https://fonts.googleapis.com/css2?family=Ubuntu+Mono&display=swap");
@import url("https://use.fontawesome.com/releases/v5.15.3/css/all.css");

body {
  font-family: "Ubuntu Mono", monospace;
  background: #313131;
}
</style>

<script lang="ts">
import { defineComponent } from "vue";
import Container from "./components/Container.vue";
import API, { COMServer } from "./API";
import RestartModal from "./components/RestartModal.vue";
import EditModal from "./components/EditModal.vue";
import PermissionsModal from "./components/PermissionsModal.vue";
import UserModal from "./components/UserModal.vue";
import ServerCollapse from "./components/ServerCollapse.vue";
import UsersCollapse from './components/UsersCollapse.vue';

export default defineComponent({
  components: {
    Container,
    RestartModal,
    EditModal,
    PermissionsModal,
    UserModal,
    ServerCollapse,
    UsersCollapse,
  },
  provide: {
    api: API,
  },
  async mounted() {
    this.isAdmin = await API.isAdmin();
    this.servers = await API.fetchServersList();
  },
  data() {
    return {
      servers: [] as COMServer[],
      isAdmin: false
    };
  },
});
</script>

// svelte/src/App.svelte
<script lang="ts">
	import Container from "./components/Container.svelte";
	import ServerCollapse from "./components/ServerCollapse.svelte";
	import API from "./API";
	import UsersCollapse from "./components/UsersCollapse.svelte";
	import UserModal from "./components/UserModal.svelte";
	import RestartModal from "./components/RestartModal.svelte";
	import EditModal from "./components/EditModal.svelte";
	import PermissionsModal from "./components/PermissionsModal.svelte";
	const { servers } = API;
</script>

<Container>
	{#if API.isAdmin}
		<UsersCollapse />
	{/if}
	{#each $servers as server}
		<ServerCollapse {server} />
	{/each}
	<UserModal />
	<RestartModal />
	<EditModal />
	<PermissionsModal />
</Container>

<style>
	@import url("https://fonts.googleapis.com/css2?family=Ubuntu+Mono&display=swap");
	/* @import url("https://use.fontawesome.com/releases/v5.15.3/css/all.css"); */

	:global(body) {
		font-family: "Ubuntu Mono", monospace;
		background: #313131;
	}
</style>
