// spa/src/components/UsersCollapse.vue
<template>
  <div class="root">
    <div class="header" @click="show = !show">
      <i class="fas fa-plus-circle" v-if="!show"></i>
      <i class="fas fa-minus-circle" v-else></i>
      Пользователи
    </div>
    <div class="content" v-if="show">
      <!-- <TerminalBlock
        :terminalData="terminal"
        v-for="terminal in terminals"
        :key="terminal.id"
      /> -->
      Something
    </div>
  </div>
</template>
<style scoped>
.root {
  flex-grow: 1;
}
.header {
  color: #ededed;
  font-size: 2rem;
  font-family: "Ubuntu Mono", monospace;
}
.content {
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
  justify-content: space-around;
}
</style>

<script lang="ts">
import { defineComponent } from "vue";
// import TerminalBlock from "./TerminalBlock.vue";
// import { API } from '../API';

export default defineComponent({
  // components: { TerminalBlock },
  // props: ["server"],
  async mounted() {
    // this.terminals = await this.server.fetchTerminals();
  },
  data() {
    return {
      // terminals: [],
      show: false
    };
  },
});
</script>

// svelte/src/components/UsersCollapse.svelte
<script lang="ts">
  import { FontAwesomeIcon } from "fontawesome-svelte";
  import { faCaretRight, faCaretDown } from "@fortawesome/free-solid-svg-icons";
  import UserBlock from "./UserBlock.svelte";
  import { tweened } from "svelte/motion";
  import { cubicOut } from "svelte/easing";
  import { slide } from "svelte/transition";
  import API from "../API";

  let show = false;
  const rotation = tweened(0, {
    duration: 400,
    easing: cubicOut,
  });

  const { users } = API;

  // import { defineComponent } from "vue";
  // import TerminalBlock from "./TerminalBlock.vue";

  // export default defineComponent({
  //   components: { TerminalBlock },
  //   props: ["server"],
  //   async mounted() {
  //     this.terminals = await this.server.fetchTerminals();
  //   },
  //   data() {
  //     return {
  //       terminals: [],
  //       show: false,
  //     };
  //   },
  // });
</script>

<div class="root">
  <div
    class="header"
    on:click={() => {
      show = !show;
      rotation.set(Number(show));
    }}
  >
    <FontAwesomeIcon
      icon={faCaretRight}
      transform={{ rotate: $rotation * 90 }}
    />
    Пользователи
  </div>
  {#if show}
    <div class="content" transition:slide>
      {#each $users as user}
        <UserBlock {user} />
      {/each}
    </div>
  {/if}
</div>

<style scoped>
  .root {
    flex-grow: 1;
  }
  .header {
    color: #ededed;
    font-size: 2rem;
    font-family: "Ubuntu Mono", monospace;
  }
  .content {
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    justify-content: space-around;
  }
</style>
